include ion/src/device/kernel/Makefile

ion_device_kernel_src += $(addprefix ion/src/device/n0110/kernel/drivers/, \
  board.cpp \
  cache.cpp \
  external_flash.cpp \
  fcc_id.cpp \
  flash_privileged.cpp \
  led.cpp \
  power.cpp \
)
