include ion/src/device/kernel/Makefile

ion_device_kernel_src += $(addprefix ion/src/device/n0110/kernel/, \
  boot/rt0.cpp \
  drivers/board.cpp \
  drivers/cache.cpp \
  drivers/external_flash.cpp \
  drivers/fcc_id.cpp \
  drivers/flash_privileged.cpp \
  drivers/led.cpp \
  drivers/power.cpp \
)
