ion_device_flasher_src = $(addprefix ion/src/device/n0110/flasher/, \
  boot/isr.c \
  boot/rt0.cpp \
  drivers/board.cpp \
  drivers/flash_privileged.cpp \
  drivers/flash_unprivileged.cpp \
  drivers/usb.cpp \
  main.cpp \
)

ION_DEVICE_SFLAGS = -Iion/src/device/$(MODEL)/flasher
