snapshots += Statistics::App::Snapshot
snapshot_headers += apps/statistics/app.h

app_objs += $(addprefix apps/statistics/,\
  app.o\
  box_banner_view.o\
  box_controller.o\
  box_range.o\
  box_view.o\
  calculation_controller.o\
  histogram_banner_view.o\
  histogram_controller.o\
  histogram_parameter_controller.o\
  histogram_view.o\
  store.o\
  store_controller.o\
)

i18n_files += $(addprefix apps/statistics/,\
  base.de.i18n\
  base.en.i18n\
  base.es.i18n\
  base.fr.i18n\
  base.pt.i18n\
)

app_images += apps/statistics/stat_icon.png
