ion_device_flasher_src += $(addprefix ion/src/device/flasher/, \
  boot/isr.c \
  boot/rt0.cpp \
  drivers/backlight.cpp \
  main.cpp \
)

ion_device_flasher_src += $(addprefix ion/src/device/shared/drivers/, \
  backlight.cpp \
)

ion_device_flasher_src += $(addprefix ion/src/device/n0110/shared/drivers/, \
  board.cpp \
)
