ion_device_flasher_src += $(addprefix ion/src/device/flasher/, \
  boot/isr.c \
  boot/rt0.cpp \
  drivers/backlight.cpp \
  drivers/board.cpp \
  drivers/external_flash.cpp \
  drivers/external_flash_command.cpp \
  drivers/flash_privileged.cpp \
  drivers/flash_unprivileged.cpp \
  drivers/usb.cpp \
  main.cpp \
)

ion_device_flasher_src += ion/src/device/shared/boot/rt0.cpp

ion_device_flasher_src += $(addprefix ion/src/device/shared/drivers/, \
  backlight.cpp \
  base64.cpp \
  display.cpp \
  internal_flash.cpp \
  internal_flash_otp.cpp \
  timing.cpp \
  reset.cpp \
  serial_number.cpp \
  usb.cpp \
  usb_privileged.cpp \
  usb_unprivileged.cpp \
)

ion_device_flasher_src += $(addprefix ion/src/device/n0110/shared/drivers/, \
  board.cpp \
  reset.cpp \
  usb.cpp \
)
