TOOLCHAIN=arm-none-eabi
# FIXME decide which one to use.
#COMPILER=llvm

ifeq ($(COMPILER),llvm)
CC=clang
CXX=clang++
else
CC=$(TOOLCHAIN)-gcc
CXX=$(TOOLCHAIN)-g++
endif

LD=$(TOOLCHAIN)-ld.bfd
GDB=$(TOOLCHAIN)-gdb
OBJCOPY=$(TOOLCHAIN)-objcopy
SIZE=$(TOOLCHAIN)-size

# Flags - Arch
ifeq ($(COMPILER),llvm)
  SFLAGS += -target thumbv7em-unknown-eabi
else
  SFLAGS += -mthumb -march=armv7e-m -mfloat-abi=hard
endif
SFLAGS += -mcpu=cortex-m4 -mfpu=fpv4-sp-d16

# Platform configuration
USE_LIBA=1
