ion_device_bench_src += $(addprefix ion/src/device/n0110/bench/drivers/, \
  board.cpp \
  console.cpp \
)

ion_device_bench_src += $(addprefix ion/src/device/n0110/bench/, \
  command_handler.cpp \
  command_list.cpp \
  main.cpp \
)

ION_DEVICE_SFLAGS = -Iion/src/device/$(MODEL)/bench
