ion_device_bench_src += $(addprefix ion/src/device/n0110/bench/command/, \
  adc.cpp \
  backlight.cpp \
  charge.cpp \
  command.cpp \
  crc.cpp \
  display.cpp \
  external_flash_id.cpp \
)

ion_device_bench_src += $(addprefix ion/src/device/n0110/bench/drivers/, \
  board.cpp \
  console.cpp \
  display.cpp \
)

ion_device_bench_src += $(addprefix ion/src/device/n0110/bench/, \
  command_handler.cpp \
  command_list.cpp \
  main.cpp \
)

ION_DEVICE_SFLAGS = -Iion/src/device/$(MODEL)/bench
