app_usb_src = $(addprefix apps/usb/,\
  app.cpp \
  usb_connected_controller.cpp \
)

app_src += $(app_usb_src)

i18n_files += $(addprefix apps/usb/,\
  base.de.i18n\
  base.en.i18n\
  base.es.i18n\
  base.fr.i18n\
  base.pt.i18n\
  base.universal.i18n\
)
