app_objs += $(addprefix apps/usb/,\
  app.o\
  usb_connected_controller.o\
)

i18n_files += $(addprefix apps/usb/,\
  base.de.i18n\
  base.en.i18n\
  base.es.i18n\
  base.fr.i18n\
  base.pt.i18n\
  base.se.i18n\
  base.universal.i18n\
)
