name: Build Docker container and define variable DOCKER_RUN to run it
description: |
  Build Docker container and define DOCKER_RUN variable.
  It binds CCACHE_DIR and pass MAKEFLAGS to the container.

runs:
  using: 'composite'
  steps:
    - name: Build Docker container
      shell: bash
      run: docker build  --build-arg ABSOLUTE_PATH=`pwd`/../../ -f build/Dockerfile . --tag epsilon-builder

    - name: Define DOCKER_RUN environment variable
      shell: bash
      run: |
        CACHE_FLAGS=""
        if echo "$MAKEFLAGS" | grep -qw with-cache; then
          CACHE_FLAGS="--env CCACHE_DIR=/cache --mount type=bind,source=$(pwd)/../../ccache,target=/cache"
        fi
        echo "DOCKER_RUN=docker run -i --user=$(id -u):$(id -g) $CACHE_FLAGS --env MAKEFLAGS --mount type=bind,source=.,target=$(pwd) epsilon-builder:latest sh -c" >> $GITHUB_ENV
