name: Build Docker container and define variable DOCKER_RUN to run it

description: |
  Build Docker container and define DOCKER_RUN variable.
  It binds CCACHE_DIR and pass MAKEFLAGS to the container.

inputs:
  platform:
    description: 'The target platform for the build system inside the container'
    required: false
    default: 'linux'
  emsdk-version:
    description: 'The Emscripten SDK version to install in the container'
    required: false
    default: 'unknown'

runs:
  using: 'composite'
  steps:
    - name: Build Docker container
      shell: bash
      run: docker build -f tools/Dockerfile.${{ inputs.platform }} . --tag oasis-builder-${{ inputs.platform }} --build-arg EMSDK_VERSION=${{ inputs.emsdk-version }}

    - name: Define DOCKER_RUN environment variable
      shell: bash
      run: |
        CACHE_FOLDER=/tmp/ccache
        mkdir -p $CACHE_FOLDER
        CACHE_FLAGS="--env CCACHE_DIR=/cache --mount type=bind,source=$CACHE_FOLDER,target=/cache"
        echo "DOCKER_RUN=docker run -i --user=$(id -u):$(id -g) $CACHE_FLAGS --env MAKEFLAGS --mount type=bind,source=.,target=/monorepo oasis-builder-${{ inputs.platform }}:latest sh -c" >> $GITHUB_ENV
