snapshots += Solver::App::Snapshot
snapshot_headers += apps/solver/app.h

app_objs += $(addprefix apps/solver/,\
  app.o\
  equation_models_parameter_controller.o\
  equation.o\
  equation_store.o\
  list_controller.o\
  solutions_controller.o\
)

i18n_files += $(addprefix apps/solver/,\
  base.de.i18n\
  base.en.i18n\
  base.es.i18n\
  base.fr.i18n\
  base.pt.i18n\
)

app_images += apps/solver/solver_icon.png
