APP_NAME = voord
APP_ICON = src/icon.png

OUTPUT_DIR = output

SOURCES = $(addprefix src/,\
  alien.cpp \
  life.cpp \
  main.cpp \
  rocket.cpp \
  spaceship.cpp \
  score.cpp \
)

include ../build/external_app.mak
