objs += $(addprefix ion/platform/device/, platform.o init.o display.o framebuffer.o init_kbd.o display/dma.o display/gpio.o display/spi.o)
objs += $(addprefix ion/drivers/, st7586/st7586.o fx92kbd/fx92kbd.o)
