SFLAGS += -Iomg/include

omg_src += $(addprefix omg/src/,\
  print.cpp \
  directions.cpp \
)

tests_src += $(addprefix omg/test/,\
  bit_helper.cpp\
  print.cpp\
)

omg_bench_src = $(addprefix omg/src/,\
  print.cpp \
)

