ion_src += $(addprefix ion/src/simulator/windows/, \
  images.cpp \
  language.cpp \
  resources.rc \
)
ion_src += $(addprefix ion/src/simulator/shared/, \
  telemetry_dummy.cpp \
)

LDFLAGS += -lgdiplus
