app_src += $(addprefix apps/hardware_test/,\
  app.cpp \
  arrow_view.cpp \
  centered_screen_test_controller.cpp \
  code_128b_view.cpp \
  dead_pixels_test_controller.cpp \
  keyboard_test_controller.cpp \
  keyboard_view.cpp \
  led_test_controller.cpp \
  pop_up_controller.cpp \
  serial_number_controller.cpp \
)
