app_objs += $(addprefix apps/hardware_test/,\
  app.o\
  arrow_view.o\
  battery_test_controller.o\
  code_128b_view.o\
  keyboard_test_controller.o\
  keyboard_view.o\
  led_test_controller.o\
  pattern.o\
  pattern_view.o\
  pop_up_controller.o\
  screen_test_controller.o\
  screen_test_controller.o\
  serial_number_controller.o\
)
