SOURCES_apps += $(addprefix $(PATH_apps)/on_boarding/,$(addsuffix :-test, \
  app.cpp \
  localization_controller.cpp \
  startup_prompt_controller.cpp \
))

$(call i18n_without_universal,on_boarding/i18n/base)
