app_objs += $(addprefix apps/sequence/,\
  app.o\
  list/list_controller.o\
  list/type_parameter_controller.o\
  list/sequence_expression_cell.o\
  list/sequence_title_cell.o\
  values/values_controller.o\
  sequence.o\
  sequence_store.o\
)

app_images += apps/sequence/sequence_icon.png
