app_objs += $(addprefix apps/calcul/,\
  app.o\
  calcul.o\
  calcul_store.o\
  history_view_cell.o\
  history_controller.o\
  edit_expression_controller.o\
)

inline_images += apps/calcul/calcul_icon.png

