ion_device_src += $(addprefix ion/src/device/shared/drivers/, \
  backlight.cpp \
  battery.cpp \
  base64.cpp \
  board.cpp \
  console_uart.cpp:+consoleuart \
  console_dummy.cpp:-consoleuart \
  crc32.cpp \
  display.cpp \
  events_keyboard_platform.cpp \
  exam_mode.cpp \
  external_flash.cpp \
  flash.cpp \
  internal_flash.cpp \
  keyboard.cpp \
  led.cpp \
  power.cpp\
  random.cpp\
  reset.cpp \
  serial_number.cpp \
  swd.cpp \
  timing.cpp \
  usb.cpp \
  wakeup.cpp \
)
