#ifndef ION_DEVICE_SHARED_DRIVERS_SVCALL_H
#define ION_DEVICE_SHARED_DRIVERS_SVCALL_H

namespace Ion {
namespace Device {
namespace SVCall {


#define SVC(code) asm volatile ("svc %[immediate]"::[immediate] "I" (code))

#define SVC_BACKLIGHT_BRIGHTNESS 0
#define SVC_BACKLIGHT_INIT 1
#define SVC_BACKLIGHT_IS_INITIALIZED 2
#define SVC_BACKLIGHT_SET_BRIGHTNESS 3
#define SVC_BACKLIGHT_SHUTDOWN 4
#define SVC_BATTERY_IS_CHARGING 5
#define SVC_BATTERY_LEVEL 6
#define SVC_BATTERY_VOLTAGE 7
#define SVC_CIRCUIT_BREAKER_HAS_CHECKPOINT 8
#define SVC_CIRCUIT_BREAKER_LOAD_CHECKPOINT 9
#define SVC_CIRCUIT_BREAKER_SET_CHECKPOINT 11
#define SVC_CIRCUIT_BREAKER_STATUS 13
#define SVC_CIRCUIT_BREAKER_UNSET_CHECKPOINT 15
#define SVC_CRC32_BYTE 16
#define SVC_CRC32_WORD 17
#define SVC_DISPLAY_COLORED_TILING_SIZE_10 18
#define SVC_DISPLAY_POST_PUSH_MULTICOLOR 19
#define SVC_DISPLAY_PULL_RECT 20
#define SVC_DISPLAY_PUSH_RECT 21
#define SVC_DISPLAY_PUSH_RECT_UNIFORM 22
#define SVC_DISPLAY_UNIFORM_TILING_SIZE_10 23
#define SVC_DISPLAY_WAIT_FOR_V_BLANK 24
#define SVC_EVENTS_COPY_TEXT 25
#define SVC_EVENTS_GET_EVENT 26
#define SVC_EVENTS_IS_DEFINED 27
#define SVC_EVENTS_REPETITION_FACTOR 28
#define SVC_EVENTS_SET_SHIFT_ALPHA_STATUS 29
#define SVC_EVENTS_SHIFT_ALPHA_STATUS 30
#define SVC_FCC_ID 31
#define SVC_KEYBOARD_SCAN 32
#define SVC_LED_GET_COLOR 33
#define SVC_LED_SET_BLINKING 34
#define SVC_LED_SET_COLOR 35
#define SVC_LED_UPDATE_COLOR_WITH_PLUG_AND_CHARGE 36
#define SVC_PERSISTING_BYTES_READ 37
#define SVC_PERSISTING_BYTES_WRITE 38
#define SVC_POWER_SELECT_STANDBY_MODE 58
#define SVC_POWER_STANDBY 39
#define SVC_POWER_SUSPEND 40
#define SVC_RANDOM 41
#define SVC_RESET_CORE 42
#define SVC_SERIAL_NUMBER 43
#define SVC_SERIAL_NUMBER_COPY 47
#define SVC_TIMING_MILLIS 44
#define SVC_TIMING_MSLEEP 45
#define SVC_TIMING_USLEEP 46
#define SVC_USB_SHOULD_INTERRUPT 51
#define SVC_USB_DID_EXECUTE_DFU 50
#define SVC_USB_WILL_EXECUTE_DFU 52
#define SVC_USB_IS_PLUGGED 53
#define SVC_BOARD_SWITCH_EXECUTABLE_SLOT 54
#define SVC_FLASH_MASS_ERASE 55
#define SVC_FLASH_ERASE_SECTOR 56
#define SVC_FLASH_WRITE_MEMORY 57

}
}
}

#endif
