ifneq (,$(findstring numworks.code,${APPS_LIST}))

app_objs += $(addprefix apps/numworks/code/,\
  app.o\
  editor_controller.o\
  executor_controller.o\
  menu_controller.o\
  program.o\
)

tests += $(addprefix apps/numworks/code/test/,\
  mpprint.cpp\
)

app_images += apps/numworks/code/code_icon.png

endif
