#ifndef ION_DEVICE_N0100_SHARED_REGS_CONFIG_USART_H
#define ION_DEVICE_N0100_SHARED_REGS_CONFIG_USART_H

#define REGS_USART_SR_OFFSET 0x00
#define REGS_USART_RDR_OFFSET 0x04
#define REGS_USART_TDR_OFFSET 0x04
#define REGS_USART_BRR_OFFSET 0x08
#define REGS_USART_CR1_OFFSET 0x0C

#define REGS_USART_CR1_UE_BIT 13

#endif
