ion_device_src += $(addprefix ion/src/device/n0110/drivers/, \
  board.cpp \
  cache.cpp \
  external_flash.cpp \
  led.cpp \
  power.cpp \
  reset.cpp \
  usb.cpp \
)

LDSCRIPT ?= ion/src/device/n0110/flash.ld
