ion_device_src += $(addprefix ion/src/device/n0101/drivers/, \
  board.cpp \
  cache.cpp \
  power.cpp \
)

ion_device_src += ion/src/device/n0101/usb/stack/device.cpp

LDSCRIPT ?= ion/src/device/n0101/flash.ld
