snapshots += Graph::App::Snapshot
snapshot_headers += apps/graph/app.h

app_objs += $(addprefix apps/graph/,\
  app.o\
  cartesian_function.o\
  cartesian_function_store.o\
  function_title_cell.o\
  graph/banner_view.o\
  graph/calculation_graph_controller.o\
  graph/calculation_parameter_controller.o\
  graph/curve_parameter_controller.o\
  graph/extremum_graph_controller.o\
  graph/graph_controller.o\
  graph/graph_controller_helper.o\
  graph/graph_view.o\
  graph/integral_graph_controller.o\
  graph/intersection_graph_controller.o\
  graph/tangent_graph_controller.o\
  graph/root_graph_controller.o\
  list/list_controller.o\
  values/derivative_parameter_controller.o\
  values/function_parameter_controller.o\
  values/values_controller.o\
)

i18n_files += $(addprefix apps/graph/,\
  base.de.i18n\
  base.en.i18n\
  base.es.i18n\
  base.fr.i18n\
  base.pt.i18n\
)

app_images += apps/graph/graph_icon.png
