app_objs += $(addprefix apps/graph/,\
  graph_app.o\
  even_odd_cell.o\
  function.o\
  function_store.o\
  graph/cursor_view.o\
  graph/graph_controller.o\
  graph/graph_view.o\
  list/function_cell.o\
  list/function_expression_view.o\
  list/function_name_view.o\
  list/list_controller.o\
  list/parameter_controller.o\
  values/float_to_string.o\
  values/interval.o\
  values/title_cell.o\
  values/value_cell.o\
  values/values_controller.o\
  values/values_parameter_controller.o\
)

inline_images += apps/graph/graph_icon.png
