app_objs += $(addprefix apps/graph/,\
  app.o\
  function.o\
  function_store.o\
  function_title_cell.o\
  graph/banner_view.o\
  graph/curve_parameter_controller.o\
  graph/goto_parameter_controller.o\
  graph/graph_controller.o\
  graph/graph_view.o\
  graph/initialisation_parameter_controller.o\
  list/list_controller.o\
  values/abscissa_parameter_controller.o\
  values/derivative_parameter_controller.o\
  values/function_parameter_controller.o\
  values/interval.o\
  values/interval_parameter_controller.o\
  values/values_controller.o\
)

app_images += apps/graph/graph_icon.png
