APP_NAME = rpn
APP_ICON = src/icon.png

OUTPUT_DIR = output

SOURCES = $(addprefix src/,\
  converter.cpp \
  input_field.cpp \
  main.cpp \
  store.cpp \
  view.cpp \
)

include ../build/external_app.mak
