app_on_boarding_src = $(addprefix apps/on_boarding/,\
  app.cpp \
  localization_controller.cpp \
  prompt_controller.cpp \
)

apps_src += $(app_on_boarding_src)

i18n_files += $(call i18n_without_universal_for,on_boarding/base)
