src += $(addprefix ion/src/emscripten/, \
  display.cpp \
  events_keyboard.cpp \
  main.cpp \
)

src += $(addprefix ion/src/shared/, \
  crc32.cpp \
  events.cpp \
  events_modifier.cpp \
  power.cpp \
  random.cpp \
  timing.cpp \
  dummy/backlight.cpp \
  dummy/battery.cpp \
  dummy/display.cpp \
  dummy/fcc_id.cpp \
  dummy/led.cpp \
  dummy/serial_number.cpp \
  dummy/stack.cpp \
  dummy/usb.cpp \
)
