objs += $(addprefix ion/src/emscripten/, \
  display.o \
  events_keyboard.o \
  main.o \
)

objs += $(addprefix ion/src/shared/, \
  crc32.o \
  crc32_padded.o \
  events.o \
  events_modifier.o \
  power.o \
  random.o \
  timing.o \
  dummy/backlight.o \
  dummy/battery.o \
  dummy/fcc_id.o \
  dummy/led.o \
  dummy/serial_number.o \
  dummy/stack.o \
  dummy/usb.o \
)
