app_objs += $(addprefix apps/regression/,\
  app.o\
  banner_view.o\
  calculation_controller.o\
  data.o\
  even_odd_double_buffer_text_cell.o\
  graph_controller.o\
  graph_view.o\
  initialisation_parameter_controller.o\
)

app_images += apps/regression/regression_icon.png
