ion_device_src += $(addprefix ion/src/device/n0100/drivers/, \
  board.cpp \
  external_flash.cpp \
  led.cpp \
  power.cpp \
  reset.cpp \
  usb.cpp \
)

ion_device_src += $(addprefix ion/src/device/n0100/boot/, \
  rt0.cpp \
)

ion_device_src += $(addprefix ion/src/device/n0100/, \
  platform_info.cpp \
)

LDSCRIPT ?= ion/src/device/n0100/flash.ld
