import argparse
import os

from cmsis_svd.parser import SVDParser
from cmsis_svd.model import SVDRegister, SVDPeripheral, SVDField


def write_autogeneration_message(file, comment_header):
    file.write(
        f"{comment_header} This file has been autogenerated. Do not edit this file manually.\n"
    )
    file.write(
        f"{comment_header} Make changes to the tools/registers/generate_peripherals.py script.\n\n"
    )


def write_field_functions(field, int_type, register_name, register_access, f):
    access_to_macro = {
        "read-write": "FIELD_RW",
        "read-only": "FIELD_RO",
        "write-only": "FIELD_WO",
    }
    f.write(
        f"  {access_to_macro[field.access or register_access]}({field.name.upper()}, {field.bit_offset}, {field.bit_width});\n"
    )


def write_register_class(register, peripheral, f, gdb_file):
    int_type = f"uint{register.size}_t"
    class_name = register.name.upper()

    # Rename register from ADC.ADC_DR or ADC1.ADC_DR to ADC.DR
    peripheral_name = peripheral.name.upper()
    if peripheral_name[-1].isdigit():
        peripheral_name = peripheral_name[:-1]
    class_name = class_name.removeprefix(peripheral_name + "_")

    address = peripheral.base_address + register.address_offset

    f.write(f"class {class_name} : public Register<{int_type}>" + " {\n")
    f.write(
        f"  REGISTER_BASICS({class_name}, 0x{address:x}, 0x{register.reset_value if 'reset_value' in register.__dict__ else 0:x});\n"
    )
    f.write("\n")

    for field in register.fields:
        write_field_functions(field, int_type, class_name, register.access, f)

    f.write("};\n\n")

    # Add function to access register in GDB file
    openocd_size_code = {8: "b", 16: "h", 32: "w", 64: "d"}.get(register.size)
    gdb_file.write(f"define get{peripheral.name.upper()}_{class_name}\n")
    gdb_file.write(f"  monitor md{openocd_size_code} 0x{address:x}\n")
    gdb_file.write("end\n")
    gdb_file.write(f"define set{peripheral.name.upper()}_{class_name}\n")
    gdb_file.write(f"  monitor mw{openocd_size_code} 0x{address:x} $arg0\n")
    gdb_file.write("end\n")
    gdb_file.write(f"define show{peripheral.name.upper()}_{class_name}\n")
    gdb_file.write(f"  set $value = *(uint{register.size}_t *)0x{address:x}\n")

    max_name_length = (
        max(len(f.name) for f in register.fields) if register.fields else 0
    )
    for field in register.fields:
        gdb_file.write(
            f'  printf "{field.name.upper():{max_name_length}} %x\\n", (($value >> {field.bit_offset}) & {(1 << field.bit_width) - 1})\n'
        )
    gdb_file.write("end\n\n")


def write_peripheral_file(peripheral, device_name, gdb_file):
    outfile = f"{peripheral.name.lower()}.h"
    with open(outfile, "w") as f:
        write_autogeneration_message(f, "//")
        f.write(f"#ifndef {device_name.upper()}_{peripheral.name.upper()}_H\n")
        f.write(f"#define {device_name.upper()}_{peripheral.name.upper()}_H\n\n")
        f.write('#include "../register.h"\n\n')
        f.write(f"namespace {device_name.upper()}" + " {\n")
        f.write(f"struct {peripheral.name.upper()}" + " {\n\n")
        for register in peripheral.registers:
            write_register_class(register, peripheral, f, gdb_file)
        f.write("};\n")
        f.write("}\n\n")
        f.write("#endif")


def main():
    parser = argparse.ArgumentParser(
        description="Generate C++ headers for peripheral registers access, from a SVD file. Generated files are created in the <device name> directory. Also creates a <device name>.gdb file to ease registers access during debugging."
    )
    parser.add_argument(
        "input",
        metavar="inputsvd",
        nargs=1,
        help="Input SVD file to generate header from",
    )
    args = parser.parse_args()

    if args.input:
        file = args.input[0]
    else:
        return

    parser = SVDParser.for_xml_file(file)
    dev = parser.get_device()
    device_name = dev.name.lower()

    with open(f"{device_name}.gdb", "w") as gdb_file:
        write_autogeneration_message(gdb_file, "#")
        os.makedirs(device_name, exist_ok=True)
        os.chdir(device_name)
        for peripheral in dev.peripherals:
            write_peripheral_file(peripheral, device_name, gdb_file)

    print(f"Done generating headers for {device_name}.")
    print(
        f'You can now copy the "register.h" file and the "{device_name}" directory to you hardware interface module.'
    )


if __name__ == "__main__":
    main()
