app_objs += $(addprefix apps/calculation/,\
  app.o\
  calculation.o\
  calculation_store.o\
  evaluate_context.o\
  selectable_table_view.o\
  history_view_cell.o\
  history_controller.o\
  edit_expression_controller.o\
  pretty_print_view.o\
  text_field.o\
)

app_images += apps/calculation/calculation_icon.png

