app_objs += $(addprefix apps/calculation/,\
  app.o\
  calculation.o\
  calculation_store.o\
  edit_expression_controller.o\
  history_view_cell.o\
  history_controller.o\
  local_context.o\
  output_expressions_view.o\
  scrollable_expression_view.o\
  scrollable_output_expressions_view.o\
  selectable_table_view.o\
  text_field.o\
)

tests += $(addprefix apps/calculation/test/,\
  calculation_store.cpp\
)
test_objs += $(addprefix apps/calculation/, calculation.o calculation_store.o)

app_images += apps/calculation/calculation_icon.png

