ion_device_src += $(addprefix ion/src/device/bootloader/drivers/, \
  board.cpp \
  cache.cpp \
  external_flash.cpp \
  led.cpp \
  power.cpp \
  reset.cpp \
  usb.cpp \
)

ion_device_src += $(addprefix ion/src/device/bootloader/drivers/, \
  board.cpp \
  cache.cpp \
  external_flash.cpp \
  led.cpp \
  power.cpp \
  reset.cpp \
  usb.cpp \
)

ion_device_src += $(addprefix ion/src/device/bootloader/boot/, \
  rt0.cpp \
)

ion_device_src += $(addprefix ion/src/device/bootloader/, \
  platform_info.cpp \
)

SLOT ?= A

LDSCRIPT ?= ion/src/device/bootloader/bootloader.$(SLOT).ld
