app_home_src = $(addprefix apps/home/,\
  app.cpp \
  app_cell.cpp \
  controller.cpp \
)

apps_src += $(app_home_src)

i18n_files += $(addprefix apps/home/,\
  base.de.i18n \
  base.en.i18n \
  base.es.i18n \
  base.fr.i18n \
  base.pt.i18n \
)
