ion_device_userland_src += $(addprefix ion/src/device/userland/, \
  boot/entry_point.c \
  boot/rt0.cpp \
  drivers/backlight.cpp \
  drivers/battery.cpp \
  drivers/display.cpp \
  drivers/events.cpp \
  drivers/events_keyboard_platform.cpp \
  drivers/keyboard.cpp \
  drivers/timing.cpp \
  drivers/usb.cpp \
)

