ion_device_kernel_src += $(addprefix ion/src/device/kernel/, \
  boot/isr.c \
  boot/rt0.cpp \
  drivers/backlight.cpp \
  drivers/battery.cpp \
  drivers/board.cpp \
  drivers/console_dummy.cpp \
  drivers/cortex_control.s \
  drivers/crc32.cpp \
  drivers/display.cpp \
  drivers/keyboard.cpp \
  drivers/led.cpp \
  drivers/svcall_handler.cpp \
  drivers/svcall_handler_as.s \
  drivers/swd.cpp \
  drivers/timing.cpp \
  main.cpp \
)

ion_device_kernel_src += $(addprefix ion/src/shared/, \
  keyboard_queue.cpp \
)

