ion_device_kernel_src += $(addprefix ion/src/device/kernel/, \
  boot/isr.c \
  boot/rt0.cpp \
  drivers/backlight.cpp \
  drivers/battery.cpp \
  drivers/board.cpp \
  drivers/circuit_breaker.cpp \
  drivers/cortex_control.s \
  drivers/crc32.cpp \
  drivers/dfu.cpp \
  drivers/dfu_relocated.cpp \
  drivers/display.cpp \
  drivers/events.cpp \
  drivers/keyboard.cpp \
  drivers/keyboard_queue.cpp \
  drivers/led.cpp \
  drivers/persisting_bytes.cpp \
  drivers/power.cpp \
  drivers/random.cpp \
  drivers/svcall_handler.cpp \
  drivers/svcall_handler_as.s \
  drivers/swd.cpp \
  drivers/timing.cpp \
  drivers/wakeup.cpp \
  main.cpp \
)
