SFLAGS += -Ilibaxx/include

src += $(addprefix libaxx/src/, new.cpp)
src += $(addprefix libaxx/src/cxxabi/, atexit.cpp pure_virtual.cpp)
src += $(addprefix libaxx/include/external/libcxx/, complex.cpp)
