SFLAGS += -Ilibaxx/include

libaxx_src += $(addprefix libaxx/src/, new.cpp)
libaxx_src += $(addprefix libaxx/src/cxxabi/, atexit.cpp pure_virtual.cpp)
libaxx_src += $(addprefix libaxx/include/external/libcxx/, complex.cpp)
