include ion/src/device/shared/usb/Makefile

ion_device_shared_bootloader_kernel_src += $(addprefix ion/src/device/shared/, \
  boot/rt0.cpp \
  drivers/base64.cpp \
  drivers/external_flash.cpp \
  drivers/flash.cpp \
  drivers/internal_flash.cpp \
  drivers/reset.cpp \
  drivers/serial_number.cpp \
  drivers/timing.cpp \
  drivers/usb.cpp \
)

ion_device_userland_src += $(addprefix ion/src/device/shared/, \
  boot/rt0.cpp \
)
