include ion/src/device/boot/Makefile
objs += $(addprefix ion/src/device/, init.o heap.o)
objs += $(addprefix ion/src/device/display/,\
  display.o\
  dma.o\
  framebuffer.o\
  gpio.o\
  spi.o\
  st7789.o\
)
objs += $(addprefix ion/src/device/keyboard/, keyboard.o)
