ifneq (,$(findstring numworks.regression,${APPS_LIST}))

app_objs += $(addprefix apps/numworks/regression/,\
  app.o\
  banner_view.o\
  calculation_controller.o\
  even_odd_double_buffer_text_cell.o\
  go_to_parameter_controller.o\
  graph_controller.o\
  graph_view.o\
  initialisation_parameter_controller.o\
  prediction_parameter_controller.o\
  store.o\
  store_controller.o\
)

app_images += apps/numworks/regression/regression_icon.png

endif
