SFLAGS += -Iescher/include

objs += $(addprefix escher/src/,\
  childless_view.o\
  solid_color_view.o\
  tab_view.o\
  tab_view_controller.o\
  text_view.o\
  view.o\
  view_controller.o\
  window.o\
)
