include ion/src/device/kernel/Makefile

ion_device_kernel_src += $(addprefix ion/src/device/n0100/kernel/, \
  boot/rt0.cpp \
  drivers/board.cpp \
  drivers/cache.cpp \
  drivers/cortex_control.s \
  drivers/fcc_id.cpp \
  drivers/led.cpp \
  drivers/power.cpp \
  drivers/usb.cpp \
)
