ifneq (,$(findstring numworks.settings,${APPS_LIST}))

app_objs += $(addprefix apps/numworks/settings/,\
  app.o\
  main_controller.o\
  settings_node.o\
  sub_controller.o\
)

app_images += apps/numworks/settings/settings_icon.png

endif

