#ifndef POINCARE_H
#define POINCARE_H

#define MATRICES_ARE_DEFINED 1

#include <poincare/absolute_value_layout.h>
#include <poincare/binomial_coefficient_layout.h>
#include <poincare/bracket_pair_layout.h>
#include <poincare/char_layout.h>
#include <poincare/ceiling_layout.h>
#include <poincare/condensed_sum_layout.h>
#include <poincare/conjugate_layout.h>
#include <poincare/empty_layout.h>
#include <poincare/floor_layout.h>
#include <poincare/fraction_layout.h>
#include <poincare/horizontal_layout.h>
#include <poincare/integral_layout.h>
#include <poincare/layout_cursor.h>
#include <poincare/layout.h>
#include <poincare/left_parenthesis_layout.h>
#include <poincare/left_square_bracket_layout.h>
#include <poincare/matrix_layout.h>
#include <poincare/nth_root_layout.h>
#include <poincare/product_layout.h>
#include <poincare/right_parenthesis_layout.h>
#include <poincare/right_square_bracket_layout.h>
#include <poincare/square_bracket_layout.h>
#include <poincare/sum_layout.h>
#include <poincare/vertical_offset_layout.h>

#include <poincare/absolute_value.h>
#include <poincare/addition.h>
#include <poincare/arc_cosine.h>
#include <poincare/arc_sine.h>
#include <poincare/arc_tangent.h>
#include <poincare/binomial_coefficient.h>
#include <poincare/complex_argument.h>
#include <poincare/confidence_interval.h>
#include <poincare/conjugate.h>
#include <poincare/context.h>
#include <poincare/cosine.h>
#include <poincare/ceiling.h>
#include <poincare/decimal.h>
#include <poincare/derivative.h>
#include <poincare/determinant.h>
#include <poincare/division.h>
#include <poincare/division_quotient.h>
#include <poincare/division_remainder.h>
#include <poincare/empty_expression.h>
#include <poincare/equal.h>
#include <poincare/expression.h>
#include <poincare/factor.h>
#include <poincare/factorial.h>
#include <poincare/float.h>
#include <poincare/floor.h>
#include <poincare/frac_part.h>
#include <poincare/global_context.h>
#include <poincare/great_common_divisor.h>
#include <poincare/hyperbolic_arc_cosine.h>
#include <poincare/hyperbolic_arc_sine.h>
#include <poincare/hyperbolic_arc_tangent.h>
#include <poincare/hyperbolic_cosine.h>
#include <poincare/hyperbolic_sine.h>
#include <poincare/hyperbolic_tangent.h>
#include <poincare/imaginary_part.h>
#include <poincare/infinity.h>
#include <poincare/integer.h>
#include <poincare/integral.h>
#include <poincare/least_common_multiple.h>
#include <poincare/logarithm.h>
#include <poincare/matrix.h>
#include <poincare/matrix_complex.h>
#include <poincare/matrix_dimension.h>
#include <poincare/matrix_inverse.h>
#include <poincare/matrix_trace.h>
#include <poincare/matrix_transpose.h>
#include <poincare/multiplication.h>
#include <poincare/naperian_logarithm.h>
#include <poincare/nth_root.h>
#include <poincare/number.h>
#include <poincare/opposite.h>
#include <poincare/parenthesis.h>
#include <poincare/permute_coefficient.h>
#include <poincare/power.h>
#include <poincare/prediction_interval.h>
#include <poincare/preferences.h>
#include <poincare/print_float.h>
#include <poincare/product.h>
#include <poincare/randint.h>
#include <poincare/random.h>
#include <poincare/rational.h>
#include <poincare/real_part.h>
#include <poincare/round.h>
#include <poincare/sine.h>
#include <poincare/square_root.h>
#include <poincare/store.h>
#include <poincare/subtraction.h>
#include <poincare/sum.h>
#include <poincare/symbol.h>
#include <poincare/tangent.h>
#include <poincare/undefined.h>
#include <poincare/variable_context.h>

#endif
