bench_src += $(addprefix ion/src/device/bench/, \
  bench.cpp \
  command_handler.cpp \
  command_list.cpp \
  runner.cpp \
)

bench_src += $(addprefix ion/src/device/bench/command/, \
  adc.cpp \
  backlight.cpp \
  charge.cpp \
  command.cpp \
  display.cpp \
  exit.cpp \
  keyboard.cpp \
  led.cpp \
  mcu_serial.cpp \
  ping.cpp \
  print.cpp \
  reset.cpp \
  sleep.cpp \
  stop.cpp \
  standby.cpp \
  vblank.cpp \
  write_external.cpp \
)
