#include <registers/gpio.h>

#define GPIOA_BASE 0x40020000
GPIO_MODER_t * GPIOA_MODER = (void *)(GPIOA_BASE);

#define GPIOB_BASE 0x40020400
GPIO_MODER_t * GPIOB_MODER = (GPIO_MODER_t *)(GPIOB_BASE);

#define GPIOC_BASE 0x40020800
GPIO_MODER_t * GPIOC_MODER = (GPIO_MODER_t *)(GPIOC_BASE);

#define GPIOD_BASE 0x40020C00
GPIO_MODER_t * GPIOD_MODER = (GPIO_MODER_t *)(GPIOD_BASE);

#define GPIOE_BASE 0x40021000
GPIO_MODER_t * GPIOE_MODER = (GPIO_MODER_t *)(GPIOE_BASE);

#define GPIOF_BASE 0x40021400
GPIO_MODER_t * GPIOF_MODER = (GPIO_MODER_t *)(GPIOF_BASE);

#define GPIOG_BASE 0x40021800
GPIO_MODER_t * GPIOG_MODER = (GPIO_MODER_t *)(GPIOG_BASE);

#define GPIOH_BASE 0x40021C00
GPIO_MODER_t * GPIOH_MODER = (GPIO_MODER_t *)(GPIOH_BASE);

#define GPIOI_BASE 0x40022000
GPIO_MODER_t * GPIOI_MODER = (GPIO_MODER_t *)(GPIOI_BASE);

#define GPIOJ_BASE 0x40022400
GPIO_MODER_t * GPIOJ_MODER = (GPIO_MODER_t *)(GPIOJ_BASE);

#define GPIOK_BASE 0x40022800
GPIO_MODER_t * GPIOK_MODER = (GPIO_MODER_t *)(GPIOK_BASE);

GPIO_MODER_t * GPIO_MODER(GPIO_t gpio) {
  GPIO_MODER_t * gpioModeRegisters[11] = {
    GPIOA_MODER,
    GPIOB_MODER,
    GPIOC_MODER,
    GPIOD_MODER,
    GPIOE_MODER,
    GPIOF_MODER,
    GPIOG_MODER,
    GPIOH_MODER,
    GPIOI_MODER,
    GPIOJ_MODER,
    GPIOK_MODER
  };
  return gpioModeRegisters[gpio];
}
