#include <registers/gpio.h>

#define GPIOA_BASE 0x40020000
#define GPIOB_BASE 0x40020400
#define GPIOC_BASE 0x40020800
#define GPIOD_BASE 0x40020C00
#define GPIOE_BASE 0x40021000
#define GPIOF_BASE 0x40021400
#define GPIOG_BASE 0x40021800
#define GPIOH_BASE 0x40021C00
#define GPIOI_BASE 0x40022000
#define GPIOJ_BASE 0x40022400
#define GPIOK_BASE 0x40022800

#pragma mark - GPIO port mode registers

GPIO_MODER_t * GPIOA_MODER = (GPIO_MODER_t *)(GPIOA_BASE);
GPIO_MODER_t * GPIOB_MODER = (GPIO_MODER_t *)(GPIOB_BASE);
GPIO_MODER_t * GPIOC_MODER = (GPIO_MODER_t *)(GPIOC_BASE);
GPIO_MODER_t * GPIOD_MODER = (GPIO_MODER_t *)(GPIOD_BASE);
GPIO_MODER_t * GPIOE_MODER = (GPIO_MODER_t *)(GPIOE_BASE);
GPIO_MODER_t * GPIOF_MODER = (GPIO_MODER_t *)(GPIOF_BASE);
GPIO_MODER_t * GPIOG_MODER = (GPIO_MODER_t *)(GPIOG_BASE);
GPIO_MODER_t * GPIOH_MODER = (GPIO_MODER_t *)(GPIOH_BASE);
GPIO_MODER_t * GPIOI_MODER = (GPIO_MODER_t *)(GPIOI_BASE);
GPIO_MODER_t * GPIOJ_MODER = (GPIO_MODER_t *)(GPIOJ_BASE);
GPIO_MODER_t * GPIOK_MODER = (GPIO_MODER_t *)(GPIOK_BASE);

GPIO_MODER_t * GPIO_MODER(GPIO_t gpio) {
  GPIO_MODER_t * gpioModeRegisters[11] = {
    GPIOA_MODER,
    GPIOB_MODER,
    GPIOC_MODER,
    GPIOD_MODER,
    GPIOE_MODER,
    GPIOF_MODER,
    GPIOG_MODER,
    GPIOH_MODER,
    GPIOI_MODER,
    GPIOJ_MODER,
    GPIOK_MODER
  };
  return gpioModeRegisters[gpio];
}

#pragma mark - GPIO port output type registers

GPIO_OTYPER_t * GPIOA_OTYPER = (GPIO_OTYPER_t *)(GPIOA_BASE + 0x4);
GPIO_OTYPER_t * GPIOB_OTYPER = (GPIO_OTYPER_t *)(GPIOB_BASE + 0x4);
GPIO_OTYPER_t * GPIOC_OTYPER = (GPIO_OTYPER_t *)(GPIOC_BASE + 0x4);
GPIO_OTYPER_t * GPIOD_OTYPER = (GPIO_OTYPER_t *)(GPIOD_BASE + 0x4);
GPIO_OTYPER_t * GPIOE_OTYPER = (GPIO_OTYPER_t *)(GPIOE_BASE + 0x4);
GPIO_OTYPER_t * GPIOF_OTYPER = (GPIO_OTYPER_t *)(GPIOF_BASE + 0x4);
GPIO_OTYPER_t * GPIOG_OTYPER = (GPIO_OTYPER_t *)(GPIOG_BASE + 0x4);
GPIO_OTYPER_t * GPIOH_OTYPER = (GPIO_OTYPER_t *)(GPIOH_BASE + 0x4);
GPIO_OTYPER_t * GPIOI_OTYPER = (GPIO_OTYPER_t *)(GPIOI_BASE + 0x4);
GPIO_OTYPER_t * GPIOJ_OTYPER = (GPIO_OTYPER_t *)(GPIOJ_BASE + 0x4);
GPIO_OTYPER_t * GPIOK_OTYPER = (GPIO_OTYPER_t *)(GPIOK_BASE + 0x4);

GPIO_OTYPER_t * GPIO_OTYPER(GPIO_t gpio) {
  GPIO_OTYPER_t * gpioOutputTypeRegisters[11] = {
    GPIOA_OTYPER,
    GPIOB_OTYPER,
    GPIOC_OTYPER,
    GPIOD_OTYPER,
    GPIOE_OTYPER,
    GPIOF_OTYPER,
    GPIOG_OTYPER,
    GPIOH_OTYPER,
    GPIOI_OTYPER,
    GPIOJ_OTYPER,
    GPIOK_OTYPER
  };
  return gpioOutputTypeRegisters[gpio];
}

#pragma mark - GPIO port output speed registers

GPIO_OSPEEDR_t * GPIOA_OSPEEDR = (GPIO_OSPEEDR_t *)(GPIOA_BASE + 0x8);
GPIO_OSPEEDR_t * GPIOB_OSPEEDR = (GPIO_OSPEEDR_t *)(GPIOB_BASE + 0x8);
GPIO_OSPEEDR_t * GPIOC_OSPEEDR = (GPIO_OSPEEDR_t *)(GPIOC_BASE + 0x8);
GPIO_OSPEEDR_t * GPIOD_OSPEEDR = (GPIO_OSPEEDR_t *)(GPIOD_BASE + 0x8);
GPIO_OSPEEDR_t * GPIOE_OSPEEDR = (GPIO_OSPEEDR_t *)(GPIOE_BASE + 0x8);
GPIO_OSPEEDR_t * GPIOF_OSPEEDR = (GPIO_OSPEEDR_t *)(GPIOF_BASE + 0x8);
GPIO_OSPEEDR_t * GPIOG_OSPEEDR = (GPIO_OSPEEDR_t *)(GPIOG_BASE + 0x8);
GPIO_OSPEEDR_t * GPIOH_OSPEEDR = (GPIO_OSPEEDR_t *)(GPIOH_BASE + 0x8);
GPIO_OSPEEDR_t * GPIOI_OSPEEDR = (GPIO_OSPEEDR_t *)(GPIOI_BASE + 0x8);
GPIO_OSPEEDR_t * GPIOJ_OSPEEDR = (GPIO_OSPEEDR_t *)(GPIOJ_BASE + 0x8);
GPIO_OSPEEDR_t * GPIOK_OSPEEDR = (GPIO_OSPEEDR_t *)(GPIOK_BASE + 0x8);

GPIO_OSPEEDR_t * GPIO_OSPEEDR(GPIO_t gpio) {
  GPIO_OSPEEDR_t * gpioOutputSpeedRegisters[11] = {
    GPIOA_OSPEEDR,
    GPIOB_OSPEEDR,
    GPIOC_OSPEEDR,
    GPIOD_OSPEEDR,
    GPIOE_OSPEEDR,
    GPIOF_OSPEEDR,
    GPIOG_OSPEEDR,
    GPIOH_OSPEEDR,
    GPIOI_OSPEEDR,
    GPIOJ_OSPEEDR,
    GPIOK_OSPEEDR
  };
  return gpioOutputSpeedRegisters[gpio];
}

