name: Device build
on:
  workflow_dispatch:
    inputs:
      beta:
        type: boolean
        default: false

env:
  MAKEFLAGS: ${{ vars.MAKEFLAGS }}
  BETA: ${{ fromJSON(github.event.inputs.beta) && '.beta' || ''  }}

jobs:
  build:
    runs-on: ${{ fromJSON(vars.EPSILON_RUNNER_LABELS) }}
    steps:
      - name: Download toolchain
        uses: numworks/setup-arm-toolchain@latest
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        run: tools/setup.sh
      # Not using matrix strategy to avoid multiplying setups and uploads.
      - name: Build n0110
        run: make PLATFORM=n0110 epsilon.onboarding$BETA.dfu epsilon.onboarding$BETA.allow3rdparty.dfu
      - name: Build n0115
        run: make PLATFORM=n0115 epsilon.onboarding$BETA.dfu epsilon.onboarding$BETA.allow3rdparty.dfu
      - name: Build n0120
        run: make PLATFORM=n0120 EMBED_EXTRA_DATA=1 epsilon.onboarding$BETA.dfu epsilon.onboarding$BETA.allow3rdparty.dfu
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: unsigned-device-builds
          path: epsilon/output/release/*/epsilon*dfu
          retention-days: 7
