name: Android Build
on:
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        default: false

env:
  MAKEFLAGS: ${{ vars.MAKEFLAGS }}

jobs:
  build:
    runs-on: ${{ fromJSON(vars.EPSILON_CACHED_RUNNER_LABELS) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build container and define DOCKER_RUN
        uses: ./.github/actions/docker-builder
        with:
          platform: android
      - run: $DOCKER_RUN "make -C epsilon DEBUG=${{ fromJSON(github.event.inputs.debug) && '1' || '0' }} CCACHE=0 PLATFORM=android epsilon_aligned.apk"
      - name: Upload apk
        uses: actions/upload-artifact@v4
        with:
          name: unsigned-epsilon-android.apk
          path: epsilon/output/${{ fromJSON(github.event.inputs.debug) && 'debug' || 'release' }}/android/epsilon_aligned.apk
          retention-days: 3
      - name: Upload debug symbols
        uses: actions/upload-artifact@v4
        with:
          name: android-debug-symbols.zip
          path: epsilon/output/${{ fromJSON(github.event.inputs.debug) && 'debug' || 'release' }}/android/app/outputs/native-debug-symbols/release/native-debug-symbols.zip
          retention-days: 3
