name: Web Build
on:
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        default: false

env:
  MAKEFLAGS: ${{ vars.MAKEFLAGS }}
  DEBUG: ${{ fromJSON(github.event.inputs.debug) && '1' || '0' }}

jobs:
  build:
    runs-on: ${{ fromJSON(vars.EPSILON_RUNNER_LABELS) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Read Emscripten version
        run: echo "EMSDK_VERSION=$(cat .emsdk-version)" >> $GITHUB_ENV
      - name: Build container and define DOCKER_RUN
        uses: ./.github/actions/docker-builder
        with:
          platform: web
          emsdk-version: ${{ env.EMSDK_VERSION }}
      - name: Build
        run: $DOCKER_RUN "make DEBUG=$DEBUG PLATFORM=web epsilon.html epsilon.htmlpack.zip"
      - name: Upload epsilon.html
        uses: actions/upload-artifact@v4
        with:
          name: epsilon.html
          path: epsilon/output/${{ fromJSON(github.event.inputs.debug) && 'debug' || 'release' }}/web/epsilon.html
          retention-days: 3
      - name: Upload htmlpack.zip
        uses: actions/upload-artifact@v4
        with:
          name: htmlpack.zip
          path: epsilon/output/${{ fromJSON(github.event.inputs.debug) && 'debug' || 'release' }}/web/epsilon.htmlpack.zip
          retention-days: 3
