name: Continuous Integration

on:
  # Running CI on every push would be better, but ci performances are limited for now.
  # push:
  #   branches: [ master, 'version-*' ]
  pull_request:
    paths-ignore:
      - '**/*.md'
      - 'poincare/doc/**'
      - 'epsilon/tests/**'
      - '**/scandium/**'
      - 'epsilon/external_apps/**'

  workflow_dispatch:
    inputs:
      device:
        type: boolean
        default: false
      android:
        type: boolean
        default: false
      windows:
        type: boolean
        default: false
      macos:
        type: boolean
        default: false
      ios:
        type: boolean
        default: false
      web:
        type: boolean
        default: false

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  MAKEFLAGS: ${{ vars.MAKEFLAGS_CACHED }}

jobs:
  android:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    if: ${{ (fromJSON(vars.ADVANCED_JOBS) || fromJSON(github.event.inputs.android)) }}
    env:
      MAKEFLAGS: '-j2'
    steps:
      - run: $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "ndk;22.1.7171670"
      - uses: actions/checkout@v4
      - run: tools/setup.sh --only-simulator
      - run: make -C epsilon PLATFORM=simulator TARGET=android ASSERTIONS=1 test.apk
      - run: make -C epsilon PLATFORM=simulator TARGET=android ASSERTIONS=1 epsilon.apk
      - uses: actions/upload-artifact@master
        with:
          name: epsilon-android.apk
          path: epsilon/output/debug/optimized/android/epsilon.apk
  device:
    timeout-minutes: 15
    runs-on: ${{ fromJSON(vars.EPSILON_CACHED_RUNNER_LABELS) }}
    if: ${{ (fromJSON(vars.ADVANCED_JOBS) || fromJSON(github.event.inputs.device)) }}
    strategy:
      matrix:
        model: [n0110, n0115, n0120]
    env:
      MAKEFLAGS: ${{ vars.MAKEFLAGS_CACHED }}
    steps:
      - uses: actions/checkout@v4

      - name: Build container and define DOCKER_RUN
        uses: ./.github/actions/docker-builder

      - name: Check for core
        id: core
        run: '[[ -e shared/ion/src/device/core ]]'
        continue-on-error: true
      - name: Disable core directory
        if: ${{ steps.core.outcome == 'success' }}
        run: mv shared/ion/src/device/core shared/ion/src/device/core-disable
      - name: Build userlands
        # Since both slots have the exact same amount of Flash reserved, it is pointless to build both the A and B elfs for every variant.
        # As an exception, because we'll build epsilon.dfu that on both userland.A.elf and userland.B.elf, we still build those here
        # TODO: It is also probably useless to build so many variants
        run: $DOCKER_RUN "make -C epsilon PLATFORM=${{ matrix.model }} userland.A.elf userland.B.elf userland.allow3rdparty.A.elf userland.onboarding.A.elf userland.onboarding.allow3rdparty.A.elf userland.onboarding.update.A.elf userland.onboarding.beta.A.elf userland.onboarding.beta.allow3rdparty.A.elf"
      - name: Restore core directory
        if: ${{ steps.core.outcome == 'success' }}
        run: mv shared/ion/src/device/core-disable shared/ion/src/device/core
      - name: Build epsilon
        if: ${{ steps.core.outcome == 'success' }}
        run: $DOCKER_RUN "make -C epsilon PLATFORM=${{ matrix.model }} epsilon.dfu"
      - name: Build flasher
        if: ${{ steps.core.outcome == 'success' }}
        run: $DOCKER_RUN "make -C epsilon PLATFORM=${{ matrix.model }} flasher.dfu"
      - name: Build bench
        if: ${{ steps.core.outcome == 'success' }}
        run: $DOCKER_RUN "make -C epsilon PLATFORM=${{ matrix.model }} bench.ram.dfu"
  windows:
    timeout-minutes: 15
    runs-on: windows-latest
    if: ${{ (fromJSON(vars.ADVANCED_JOBS) || fromJSON(github.event.inputs.windows)) }}
    defaults:
      run:
        shell: msys2 {0}
    env:
      MAKEFLAGS: '-j2'
    steps:
      - uses: msys2/setup-msys2@v2
        with:
          msystem: mingw64
          update: true
          install: >-
            git
            mingw-w64-x86_64-arm-none-eabi-gcc
      - uses: actions/checkout@v4
      - run: tools/setup.sh
      - run: make -C epsilon PLATFORM=simulator ASSERTIONS=1 epsilon.exe
      - run: make -C epsilon PLATFORM=simulator ASSERTIONS=1 test.exe
      - run: ./epsilon/output/debug/optimized/windows/test.exe --headless --limit-stack-usage
      - run: make -j8 userland.A.elf
      - uses: actions/upload-artifact@v4
        with:
          name: epsilon-windows.exe
          path: epsilon/output/debug/optimized/windows/epsilon.exe
  web:
    timeout-minutes: 15
    runs-on: ${{ fromJSON(vars.EPSILON_CACHED_RUNNER_LABELS) }}
    if: ${{ (fromJSON(vars.ADVANCED_JOBS) || fromJSON(github.event.inputs.web)) }}
    env:
      MAKEFLAGS: ${{ vars.MAKEFLAGS_CACHED }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Read Emscripten version
        run: echo "EMSDK_VERSION=$(cat .emsdk-version)" >> $GITHUB_ENV
      - name: Download emscripten
        uses: numworks/setup-emscripten@latest
        with:
          sdk: ${{ env.EMSDK_VERSION }}
      - run: tools/setup.sh --only-simulator
      - run: make -C epsilon PLATFORM=simulator TARGET=web ASSERTIONS=1 epsilon.html epsilon_test.js
      - run: node epsilon/output/debug/optimized/web/epsilon_test.js --headless --limit-stack-usage
        timeout-minutes: 5
      - uses: actions/upload-artifact@v4
        with:
          name: epsilon.html
          path: epsilon/output/debug/optimized/web/epsilon.html
          retention-days: 7
  linux:
    timeout-minutes: 15
    runs-on: ${{ fromJSON(vars.EPSILON_CACHED_RUNNER_LABELS) }}
    env:
      MAKEFLAGS: ${{ vars.MAKEFLAGS_CACHED }}
    steps:
      - uses: actions/checkout@v4

      - name: Build container and define DOCKER_RUN
        uses: ./.github/actions/docker-builder

      # TODO_PCJ: Add ASAN=1 and TIDY=1
      - name: Build epsilon.bin and test.bin
        run: $DOCKER_RUN "make -C epsilon TOOLCHAIN=host-clang PLATFORM=simulator ASSERTIONS=1 epsilon.bin epsilon_test.bin"
      - name: Run unit tests (in parallel)
        run: |
          $DOCKER_RUN "parallel --halt now,fail=1 --keep-order epsilon/output/debug/optimized/linux/epsilon_test.bin --headless --limit-stack-usage --number-of-chunks 32 --chunk-id {} ::: \$(seq 0 31)"
        id: run-tests
        continue-on-error: true
      - name: Run unit tests sequentially (if parallel run failed)
        if: steps.run-tests.outcome == 'failure'
        run: $DOCKER_RUN "rm -f core; epsilon/output/debug/optimized/linux/epsilon_test.bin --headless --limit-stack-usage || (eu-stack --core core; exit 1)"
      - uses: actions/upload-artifact@v4
        if: ${{ fromJSON(vars.ADVANCED_JOBS) }}
        with:
          name: epsilon-linux.bin
          path: epsilon/output/debug/optimized/linux/epsilon.bin
  macos:
    timeout-minutes: 15
    runs-on: macOS-latest
    if: ${{ (fromJSON(vars.ADVANCED_JOBS) || fromJSON(github.event.inputs.macos)) }}
    env:
      MAKEFLAGS: '-j2'
    steps:
      - uses: actions/checkout@v4
      - run: tools/setup.sh --only-simulator
      - run: make -C epsilon PLATFORM=simulator ASSERTIONS=1 ARCH=x86_64 epsilon_test.bin
      - run: epsilon/output/debug/optimized/macos/x86_64/epsilon_test.bin --headless --limit-stack-usage
      - run: make -C epsilon PLATFORM=simulator ASSERTIONS=1 epsilon.app
      - uses: actions/upload-artifact@v4
        with:
          name: epsilon-macos.zip
          path: epsilon/output/debug/optimized/macos/epsilon.app
  ios:
    timeout-minutes: 15
    runs-on: macOS-latest
    if: ${{ (fromJSON(vars.ADVANCED_JOBS) || fromJSON(github.event.inputs.ios)) }}
    env:
      MAKEFLAGS: '-j2'
    steps:
      - uses: actions/checkout@v4
      - run: tools/setup.sh --only-simulator
      - run: make -C epsilon PLATFORM=simulator TARGET=ios ASSERTIONS=1 epsilon.ipa
      - run: make -C epsilon PLATFORM=simulator TARGET=ios ASSERTIONS=1 test.ipa
      - run: make -C epsilon PLATFORM=simulator TARGET=ios APPLE_PLATFORM=ios-simulator
      - uses: actions/upload-artifact@v4
        with:
          name: epsilon-ios.ipa
          path: epsilon/output/debug/optimized/ios/epsilon.ipa
  poincarejs:
    timeout-minutes: 15
    runs-on: ${{ fromJSON(vars.EPSILON_CACHED_RUNNER_LABELS) }}
    env:
      MAKEFLAGS: ${{ vars.MAKEFLAGS_CACHED }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Read Emscripten version
        run: echo "EMSDK_VERSION=$(cat .emsdk-version)" >> $GITHUB_ENV
      - name: Download emscripten
        uses: numworks/setup-emscripten@latest
        with:
          sdk: ${{ env.EMSDK_VERSION }}
      - name: Setup the environment
        run: tools/setup.sh --only-simulator
      - name: Run tests with ASSERTIONS=1
        run: make -j8 -C poincare/poincarejs PLATFORM=foxglove ASSERTIONS=1 poincare.js.run
      # Ensures that minification did not break the code
      - name: Run tests with ASSERTIONS=0
        run: make -j8 -C poincare/poincarejs PLATFORM=foxglove ASSERTIONS=0 poincare.js.run
      - name: Try building the whole zipped file
        run: make -C poincare/poincarejs poincarejs.zip
      - uses: actions/upload-artifact@v4
        with:
          name: poincarejs.zip
          # TODO move poincarejs output path inside poincare
          path: poincare/poincarejs/output/release/foxglove/poincarejs.zip
          retention-days: 7
  coverage:
    name: Code Coverage
    needs: linux
    uses: ./.github/workflows/code_coverage.yml
    with:
      project-path: epsilon
      coverage-scope: ""
