name: Screenshots
on:
  pull_request:
    paths-ignore:
      - '**/*.md'
      - 'poincare/doc/**'
      - 'shared/ion/src/device/**'
      - '**/scandium/**'
      - 'epsilon/external_apps/**'

env:
  MAKEFLAGS: "${{ vars.MAKEFLAGS_CACHED }} STRICT_WARNINGS=1"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  compare_crc:
    timeout-minutes: 15
    runs-on: ${{ fromJSON(vars.EPSILON_RUNNER_LABELS_LARGE) }}
    steps:
      - name: Checkout PR's merged head
        uses: actions/checkout@v4
      - name: Build container and define DOCKER_RUN
        uses: ./.github/actions/docker-builder
      - name: Compare crc of screenshots (No CAS)
        timeout-minutes: 15
        run: |
          $DOCKER_RUN "make \
                       TOOLCHAIN=host-clang PLATFORM=simulator ASSERTIONS=1 VERBOSE=0 \
                       ARGS='--dataset tests/screenshots_dataset --no-screenshots' \
                       epsilon.compare"
      - name: Compare crc of screenshots (CAS)
        timeout-minutes: 15
        run: |
          $DOCKER_RUN "make \
                       TOOLCHAIN=host-clang PLATFORM=simulator ASSERTIONS=1 VERBOSE=0 \
                       ARGS='--dataset tests/screenshots_dataset_cas --no-screenshots' \
                       epsilon.cas.compare"
