name: Screenshots
on:
  pull_request:
  workflow_dispatch:
    inputs:
      downloadArtifacts:
        description: 'Download screenshots and executables'
        required: true
        default: 'yes'

jobs:
  compare_screenshots:
    runs-on: ${{ (github.repository == 'numworks/epsilon-internal') && 'self-hosted' || 'ubuntu-latest' }}
    steps:
      - name: Checkout PR head
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - run: build/setup.sh
      - name: Compare screenshot images
        run: ./build/screenshots/compare.sh MAKEFLAGS="-j32 PLATFORM=simulator DEBUG=1" tests/screenshots_dataset/scenari/ tests/screenshots_dataset/reference_images/ ${{ github.event.pull_request.head.sha }}
      - name: Gather screenshots
        if: ${{ github.event.inputs.downloadArtifacts == 'yes' }}
        uses: actions/upload-artifact@v2
        with:
          name: screenshots
          path: compare_output_*/
      - name: Cleanup
        if: always()
        run: rm -rf compare_output_*
