name: Build metrics

on:
  pull_request:
    paths-ignore:
      - '**/*.md'
      - 'poincare/doc/**'
      - 'tests/**'
      - '**/scandium/**'
      - 'ion/src/simulator/**'
      - 'external_apps/**'

concurrency:
  group: ${{ github.workflow }}-Epsilon-${{ github.ref }}
  cancel-in-progress: true

env:
  MAKEFLAGS: -j2

jobs:
  binary-size:
    name: Epsilon
    uses: ./.github/workflows/metrics-build.yml
    with:
      project-path: epsilon
      platform: n0120
      elfs-if-core: bootloader/bootloader.elf kernel/kernel.onboarding.beta.allow3rdparty.A.elf
      elfs: userland.onboarding.beta.allow3rdparty.A.elf
      elfs-summary-if-core: kernel/kernel.onboarding.beta.allow3rdparty.A.elf
      elfs-summary: userland.onboarding.beta.allow3rdparty.A.elf
      app-sizes: true
