name: External Apps Build
on:
  pull_request:
    paths:
      - 'external_apps/**'

env:
  MAKEFLAGS: ${{ vars.MAKEFLAGS }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  c_cpp_apps:
    runs-on: ${{ fromJSON(vars.EPSILON_RUNNER_LABELS) }}
    defaults:
      run:
        working-directory: ./epsilon
    steps:
      - name: Install toolchain
        uses: numworks/setup-arm-toolchain@latest
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup
        run: tools/setup.sh
      - uses: actions/setup-node@v4
        with:
          node-version: latest
      - name: Setup nwlink
        run: npm install -g nwlink
      - name: Build sample_c for device
        run: make -C external_apps/sample_c PLATFORM=device build
      - name: Build sample_cpp for device
        run: make -C external_apps/sample_cpp PLATFORM=device build
      - name: Build rpn_cpp for device
        run: make -C external_apps/rpn_cpp PLATFORM=device build
  rust_app:
    runs-on: ubuntu-latest
    if: 0
    defaults:
      run:
        working-directory: ./epsilon
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Go to rust external app directory
        run: cd external_apps/sample_rust
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: thumbv7em-none-eabihf
      - name: Run cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
