name: Build metrics
# read-only repo token
on:
  workflow_call:
    inputs:
      project-path:
        type: string
      platform:
        type: string
      elfs:
        type: string
      elfs-if-core:
        type: string
      elfs-summary:
        type: string
      elfs-summary-if-core:
        type: string
      app-sizes:
        type: boolean

jobs:
  binary-size:
    timeout-minutes: 15
    runs-on: ${{ fromJSON(vars.EPSILON_CACHED_RUNNER_LABELS) }}
    env:
      MAKEFLAGS: ${{ vars.MAKEFLAGS_CACHED }} PLATFORM=${{ inputs.platform }}
    steps:
      - name: Fetch target branch and PR branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 200
      - name: Find most recent ancestor of PR and target branch
        id: common_ancestor
        run: echo "commit_sha=$(git merge-base ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }})" >> $GITHUB_OUTPUT

      - name: Build container and define DOCKER_RUN
        uses: ./.github/actions/docker-builder
        with:
          platform: device

      - name: Checkout to most recent ancestor
        run: git checkout ${{ steps.common_ancestor.outputs.commit_sha }}

      - name: Check for core
        id: elfs
        run: |
          if [[ -e shared/ion/src/device/core ]]; then
            ELFS="${{ inputs.elfs }} ${{ inputs.elfs-if-core }}"
            ELFS_SUMMARY="${{ inputs.elfs-summary }} ${{ inputs.elfs-summary-if-core }}"
          else
            ELFS="${{ inputs.elfs }}"
            ELFS_SUMMARY="${{ inputs.elfs-summary }}"
          fi
          echo "elfs=$ELFS" >> $GITHUB_OUTPUT
          echo "elfs-summary=$ELFS_SUMMARY" >> $GITHUB_OUTPUT
          GOALS=$(for e in $ELFS; do basename $e; done | paste -sd' ' -)
          echo "goals=$GOALS" >> $GITHUB_OUTPUT

      - name: Build common ancestor
        run: $DOCKER_RUN "make DEBUG=0 -C ${{ inputs.project-path }} ${{ steps.elfs.outputs.goals }}"
      - name: Save ancestor build
        run: mv ${{ inputs.project-path }}/output/release/${{ inputs.platform }} base

      - name: Checkout head of PR
        run: git checkout ${{ github.event.pull_request.head.sha }}

      - name: Build head
        run: $DOCKER_RUN "make DEBUG=0 -C ${{ inputs.project-path }} ${{ steps.elfs.outputs.goals }}"
      - name: Save head build
        run: mv ${{ inputs.project-path }}/output/release/${{ inputs.platform }} head

      - name: Initialize metrics output
        run: |
          mkdir -p ./metrics-output
          echo ${{ github.event.number }} > ./metrics-output/PR_number
          echo ${{ inputs.platform }} > ./metrics-output/platform
          echo -n ${{ inputs.project-path == 'scandium' && 'Scandium' || 'Epsilon' }} > ./metrics-output/project
      - name: Binary size summary
        run: $DOCKER_RUN "\$PYTHON tools/metrics/binary_size.py @Base $(for e in ${{ steps.elfs.outputs.elfs-summary }}; do echo -n "base/$e "; done) @Head  $(for e in ${{ steps.elfs.outputs.elfs-summary }}; do echo -n "head/$e "; done) --sections @Flash .text .rodata .data @RAM .bss .data --summarize" > ./metrics-output/binary_size_summary
      - name: Binary size
        run: $DOCKER_RUN "\$PYTHON tools/metrics/binary_size.py @Base $(for e in ${{ steps.elfs.outputs.elfs }}; do echo -n "base/$e "; done) @Head  $(for e in ${{ steps.elfs.outputs.elfs }}; do echo -n "head/$e "; done) --sections .text .rodata .bss .data" > ./metrics-output/binary_size
      - name: App sizes
        if: ${{ inputs.app-sizes }}
        run: $DOCKER_RUN "\$PYTHON tools/metrics/binary_size.py @Base base/userland.onboarding.beta.allow3rdparty.A.elf @Head head/userland.onboarding.beta.allow3rdparty.A.elf --app-sizes" > ./metrics-output/app_sizes
      - name: Upload metrics output
        uses: actions/upload-artifact@v4
        with:
          name: metrics-output
          path: metrics-output/
          retention-days: 7
