name: Build metrics
# read-only repo token
on:
  pull_request:
    paths-ignore:
      - '**/*.md'
      - 'poincare/doc/**'
      - 'epsilon/tests/**'
      - 'shared/ion/src/simulator/**'
      - '**/scandium/**'
      - 'epsilon/external_apps/**'
env:
  MAKEFLAGS: ${{ vars.MAKEFLAGS_CACHED }} PLATFORM=n0120

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  binary-size:
    timeout-minutes: 15
    runs-on: ${{ fromJSON(vars.EPSILON_CACHED_RUNNER_LABELS) }}
    steps:
      - name: Fetch target branch and PR branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 200
      - name: Find most recent ancestor of PR and target branch
        id: common_ancestor
        run: echo "commit_sha=$(git merge-base ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }})" >> $GITHUB_OUTPUT

      - name: Build container and define DOCKER_RUN
        uses: ./.github/actions/docker-builder

      - name: Checkout to most recent ancestor
        run: git checkout ${{ steps.common_ancestor.outputs.commit_sha }}

      - name: Check for core
        id: core
        run: '[[ -e shared/ion/src/device/core ]]'
        continue-on-error: true
      - name: Build common ancestor bootloader and kernel for N0120
        if: ${{ steps.core.outcome == 'success' }}
        run: $DOCKER_RUN "make -C epsilon bootloader.elf kernel.onboarding.beta.allow3rdparty.A.elf"
      - name: Build common ancestor userland for N0120
        run: $DOCKER_RUN "make -C epsilon userland.onboarding.beta.allow3rdparty.A.elf"
      - name: Save ancestor build
        run: mv epsilon/output/release/n0120 base

      - name: Checkout head of PR
        run: git checkout ${{ github.event.pull_request.head.sha }}

      - name: Build head bootloader and kernel for N0120
        if: ${{ steps.core.outcome == 'success' }}
        run: $DOCKER_RUN "make -C epsilon bootloader.elf kernel.onboarding.beta.allow3rdparty.A.elf"
      - name: Build head userland for N0120
        run: $DOCKER_RUN "make -C epsilon userland.onboarding.beta.allow3rdparty.A.elf"
      - name: Save head build
        run: mv epsilon/output/release/n0120 head

      - name: Initialize metrics output
        run: |
          mkdir -p ./metrics-output
          echo ${{ github.event.number }} > ./metrics-output/PR_number
      - name: Binary size summary
        if: ${{ steps.core.outcome == 'success' }}
        run: $DOCKER_RUN "\$PYTHON build/metrics/binary_size.py @Base base/kernel/kernel.onboarding.beta.allow3rdparty.A.elf base/userland.onboarding.beta.allow3rdparty.A.elf @Head head/kernel/kernel.onboarding.beta.allow3rdparty.A.elf head/userland.onboarding.beta.allow3rdparty.A.elf --sections @Flash .text .rodata .data @RAM .bss .data --summarize" > ./metrics-output/binary_size_summary
      - name: Binary size summary (userland only)
        if: ${{ steps.core.outcome != 'success' }}
        run: $DOCKER_RUN "\$PYTHON build/metrics/binary_size.py @Base base/userland.onboarding.beta.allow3rdparty.A.elf @Head head/userland.onboarding.beta.allow3rdparty.A.elf --sections @Flash .text .rodata .data @RAM .bss .data --summarize)" > ./metrics-output/binary_size_summary
      - name: App sizes
        run: $DOCKER_RUN "\$PYTHON build/metrics/binary_size.py @Base base/userland.onboarding.beta.allow3rdparty.A.elf @Head head/userland.onboarding.beta.allow3rdparty.A.elf --app-sizes" > ./metrics-output/app_sizes
      - name: Binary size N0120
        if: ${{ steps.core.outcome == 'success' }}
        run: $DOCKER_RUN "\$PYTHON build/metrics/binary_size.py @Base base/bootloader/bootloader.elf base/kernel/kernel.onboarding.beta.allow3rdparty.A.elf base/userland.onboarding.beta.allow3rdparty.A.elf @Head head/bootloader/bootloader.elf head/kernel/kernel.onboarding.beta.allow3rdparty.A.elf head/userland.onboarding.beta.allow3rdparty.A.elf --sections .text .rodata .bss .data" > ./metrics-output/binary_size_n0120
      - name: Binary size N0120 (userland only)
        if: ${{ steps.core.outcome != 'success' }}
        run: $DOCKER_RUN "\$PYTHON build/metrics/binary_size.py @Base base/userland.onboarding.beta.allow3rdparty.A.elf @Head head/userland.onboarding.beta.allow3rdparty.A.elf --sections .text .rodata .bss .data" > ./metrics-output/binary_size_n0120
      - name: Upload metrics output
        uses: actions/upload-artifact@v4
        with:
          name: metrics-output
          path: metrics-output/
          retention-days: 7
